directories:
  mirror_module_path: True
  removed_mirror_prefix: "/Users/pprunty/GitHub/manim/projects"
  base: "/Users/pprunty/GitHub/manim/exports"
  subdirs:
    raster_images: "/images/raster"
    vector_images: "images/vector"
    pi_creature_images: "images/pi_creature/svg"
    downloads: "manim_downloads"
    # Use the default value for the rest
universal_import_line: "from manim_imports_ext import *"
window:
  position_string: UR
  monitor_index: 0
  full_screen: True  # Enable full-screen mode by default
camera:
  resolution: (3840, 2160)
  background_color: "#1C1C1C"
  fps: 60
  background_opacity: 1.0
file_writer:
  saturation: 1.5
text:
  font: "CMU Serif"
  alignment: "CENTER"
tex:
  template: "default"
embed:
  autoreload: True
ignore_manimlib_modules_on_reload: True
